1
bitzlato/barong pull request #150
Opened 2022-05-11 22:27 UTC by unloved

2022-05-13 07:16 UTC, dapi commented on app/api/v2/public/general.rb
> +        requires :status, type: 'String', desc: 'Verification status'
перечень статусов

2022-05-13 07:16 UTC, dapi commented on app/api/v2/public/general.rb
> +        requires :reason, type: 'String', desc: 'Reason if not verified'
перечень резонов

2022-05-13 07:16 UTC, dapi commented on app/models/bitzlato_user_action_freeze.rb
> +  scope :freezed_new_user, -> { active.where(reason: 'Freeze new user. Identification is required', freeze_type: 'all', admin_code: 'system') }
??? Надо осбудить

2022-05-13 07:16 UTC, dapi commented on app/services/agnessakyc_service.rb
> +  def initialize params
перечислить параметры

2022-05-13 07:17 UTC, dapi commented on app/services/agnessakyc_service.rb
> +    @user = User.find(params[:external_id])
find_by_uid || raise WTF

2022-05-13 07:20 UTC, dapi commented on app/services/agnessakyc_service.rb
> +  end
`user.verified! true`

2022-05-13 07:21 UTC, dapi commented on app/services/agnessakyc_service.rb
> +    label = user.labels.find_by(key: 'verification')
`user.verified! false`

2022-05-13 07:21 UTC, dapi commented on app/services/agnessakyc_service.rb
> +    if user.bitzlato_user.freeze_records.freezed_new_user.any?
`bitzlato_user.freezed_as_new_user?`

2022-05-13 07:29 UTC, dapi commented on app/workers/agnessakyc/notificator_worker.rb
> +      NotificatorAPI.notify(user_id, status, reason)
`Notificator.peform p2p_user_id: user.bitzlato_user.try(:id), name: 'verificationDecision', data: { userId: user_id, status: status, reason: reason } `

2022-05-13 07:30 UTC, dapi commented on app/workers/agnessakyc/notificator_worker.rb
> +  class NotificatorWorker
Не нужен

2022-05-13 07:38 UTC, dapi requested changes
мелочи

2022-05-13 07:38 UTC, dapi commented on app/services/agnessakyc_service.rb
> +    Agnessakyc::NotificatorWorker.perform_async(user.bitzlato_user.id, verified, reason)
Notificator.peform id: verfication_id, name: 'verificationDecision', data: { userId: user_id, status: status, reason: reason }

2022-05-13 07:38 UTC, dapi commented on app/services/agnessakyc_service.rb
> +    Agnessakyc::MailerWorker.perform_async(user.id, key, reason)
EventAPI.notify("system.user.#{key}", record: {reason: reason, user: user.as_json_for_event_api})

2022-05-13 07:38 UTC, dapi commented on app/workers/agnessakyc/bitzlato_unfreeze_worker.rb
> +      BitzlatoAPI.new.unfreeze_user(user_id, params)
BitzlatoClient

2022-05-17 07:15 UTC, unloved commented on app/api/v2/public/general.rb
> +        requires :reason, type: 'String', desc: 'Reason if not verified'
резон это тест от имени оператора: у вас кривая фотография и т.д.

2022-05-17 09:25 UTC, dapi commented on lib/barong/bitzlato_client.rb
> +  def key_unfreeze_user(user_id, params)
Не понял смысл этого метода

2022-05-17 09:25 UTC, dapi approved these changes

2022-05-17 10:15 UTC, dapi approved these changes

2022-05-19 07:51 UTC, merged