[#181740485] Look up user by apple_uid and email
bitzlato/barong pull request #151
Opened 2022-05-12 13:22 UTC by Nitr

2022-05-13 07:44 UTC, dapi requested changes

2022-05-13 07:44 UTC, dapi commented on app/api/v2/identity/sessions.rb
> +                user.update!(apple_uid: claims[:sub])
```
user.with_lock do
  if user.apple_uid.blank?
   user.update! apple_uid: claims[:sub]
  else 
   raise "User with email #{claims[:email]} already has apple_uid #{claims[:sub]"
 ```

2022-05-13 07:44 UTC, dapi commented on app/api/v2/identity/sessions.rb
> +              user.confirm_email! unless user.email_verified?
Если мы нашли пользователя по емайлу и емайл не был подтверждён, значит к этому аккаунту через пароль есть доступ у третьего лица и его нельзя просто так отмечать как подтвержденный.

В этом случае нужно или сбрасывать пароль или делать что-то ещё.

2022-05-13 07:44 UTC, dapi commented on db/migrate_primary/20220512125339_add_apple_uid_to_users.rb
> +    add_column :users, :apple_uid, :string
уникальный индекс

2022-05-17 07:14 UTC, dapi commented on app/api/v2/identity/sessions.rb
> +                  user.confirm_email!
А зачем ему подтверждать емайл? Можно считать уже подтвержденным

2022-05-17 09:24 UTC, dapi requested changes
Все супер, смущают два вопроса:
1. А нужно ли ему вообще подтверждать емайл?
2. Если подтверждать то вроде надо делать confirm_email! вне транзакции

2022-05-17 09:24 UTC, dapi commented on app/api/v2/identity/sessions.rb
> +                    user.confirm_email!
смущает что отправка емайла в транзакции

2022-05-17 10:17 UTC, Nitr commented on app/api/v2/identity/sessions.rb
> +                    user.confirm_email!
это не отправка

2022-05-17 10:17 UTC, Nitr commented on app/api/v2/identity/sessions.rb
> +                  user.confirm_email!
надо создать lable чтобы подтвердить

2022-05-17 10:18 UTC, dapi commented on app/api/v2/identity/sessions.rb
> +                    user.confirm_email!
Ааа..

2022-05-17 10:18 UTC, dapi approved these changes

2022-05-17 10:19 UTC, Nitr commented
> Все супер, смущают два вопроса:
> 
> 1. А нужно ли ему вообще подтверждать емайл?
> 2. Если подтверждать то вроде надо делать confirm_email! вне транзакции

1. а как он тогда будет без подтверждения с биржей работать? он вроде ничего сделать не сможет?
2. confirm_email! создает нужный label, а email отправляется другим методом.

может тогда нужно отдельное подтверждение для oauth?

2022-06-07 07:59 UTC, merged