[#181184288] Add request limits to otp endpoints
bitzlato/barong pull request #91
Opened 2022-02-16 14:39 UTC by radanisk

2022-02-17 10:20 UTC, dapi requested changes

2022-02-17 10:20 UTC, dapi commented on config/initializers/rack_attack.rb
> +    end
Надо как и в Peatio по uid тротлить, так как заголовок авторизации каждый раз новый содаётся

2022-02-17 10:23 UTC, radanisk commented on config/initializers/rack_attack.rb
> +    end
Согласен, понял это уже на тесте. )

2022-02-21 08:11 UTC, dapi approved these changes

2022-02-21 09:12 UTC, dapi commented
Качу на прод?

2022-02-21 09:15 UTC, radanisk commented
@dapi пока рано. Ожидает фронтовые правки.

2022-02-25 13:36 UTC, merged